[versions]
shadow = "9.3.1"
vineflower = "1.11.2"
junit = "5.14.3"
mockito = "5.21.0"
assertj = "3.27.7"

[libraries]
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
